inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('redstone'))
        .input(item('thermalfoundation:material', 16))
        .output(item('erebus:materials', 11))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('contenttweaker:bauxite_dust') * 2)
        .input(item('appliedenergistics2:material', 3))
        .input(item('minecraft:clay_ball'))
        .output(item('thermalfoundation:material', 68) * 5)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('water'))
        .input(item('contenttweaker:slime_shard'))
        .output(item('minecraft:slime_ball'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('essence_slurp'))
        .input(item('minecraft:paper') * 8)
        .output(item('mysticalagriculture:crafting', 5))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('water'))
        .input(item('deepmoblearning:soot_covered_redstone') * 4)
        .output(item('minecraft:redstone'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('water'))
        .input(item('contenttweaker:malachite_ore_dust'))
        .input(item('appliedenergistics2:material', 2))
        .output(item('contenttweaker:malachite_dust'))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('blueslime'))
        .input(item('exnihilocreatio:item_material', 3))
        .input(item('minecraft:sapling'))
        .output(item('tconstruct:slime_sapling'))
        .register()




inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('napalm'))
        .input(item('contenttweaker:power_core_inactive'))
        .output(item('contenttweaker:power_core_active'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('concrete'))
        .input(item('contenttweaker:electric_stone_dust') * 4)
        .input(item('contenttweaker:industrial_clay'))
        .output(item('projectred-core:resource_item') * 4)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowstone'), 0.0f)
        .input(item('mekanism:ingot', 1))
        .output(item('contenttweaker:angel_ingot'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cloud_seed'), 0.0f)
        .input(item('mekanism:ingot', 1))
        .output(item('contenttweaker:angel_ingot'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cloud_seed'), 0.0f)
        .input(item('mekanism:basicblock'))
        .output(item('contenttweaker:angel_block'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cloud_seed'), 0.0f)
        .input(item('extendedcrafting:singularity_custom', 5))
        .output(item('extendedcrafting:singularity_custom', 42))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('fire_water'), 0.0f)
        .input(item('minecraft:gold_ingot'))
        .output(item('extrautils2:ingredients', 11))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('fire_water'), 0.0f)
        .input(item('minecraft:gold_block'))
        .output(item('extrautils2:simpledecorative', 1))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('fire_water'), 0.0f)
        .input(item('extendedcrafting:singularity', 5))
        .output(item('extendedcrafting:singularity_custom', 41))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('minecraft:potato'))
        .output(item('minecraft:poisonous_potato'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 1.0f)
        .input(item('minecraft:wheat_seeds'))
        .output(item('exnihilocreatio:item_material', 3))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('minecraft:porkchop'))
        .output(item('minecraft:rotten_flesh'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('minecraft:beef'))
        .output(item('minecraft:rotten_flesh'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('minecraft:chicken'))
        .output(item('minecraft:rotten_flesh'))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('clay'))
        .input(item('contenttweaker:staffwood'))
        .input(item('tconstruct:dried_clay'))
        .output(item('contenttweaker:staffwood_clay'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowshroom_stew'))
        .input(item('contenttweaker:staffwood'))
        .input(item('mod_lavacow:cordy_shroom'))
        .input(item('mod_lavacow:bloodtooth_shroom'))
        .input(item('betternether:bone_mushroom'))
        .output(item('contenttweaker:staffwood_mushroom'))
        .register()


inWorldCrafting.fluidToFluid.recipeBuilder()
        .fluidInput(fluid('water'))
        .input(item('minecraft:dye', 15))
        .input(item('prodigytech:ash') * 3)
        .fluidOutput(fluid('ash_solution'))
        .register()
inWorldCrafting.fluidToFluid.recipeBuilder()
        .fluidInput(fluid('witchwater'))
        .input(item('thermalfoundation:material', 769) * 32)
        .input(item('contenttweaker:weak_enhancer'))
        .fluidOutput(fluid('creosote'))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('formic_acid'))
        .input(item('contenttweaker:compound_metal'))
        .output(item('contenttweaker:compound_metal2'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('druid_soup'))
        .input(item('thermalfoundation:storage_alloy', 7) * 8)
        .input(item('contenttweaker:singularity_dust'))
        .input(item('biomesoplenty:gem', 5) * 32)
        .input(item('thermalexpansion:frame'))
        .output(item('enderio:block_travel_anchor'))
        .register()


inWorldCrafting.explosion.recipeBuilder()
    .input(item('thermalfoundation:rockwool', 7))
    .output(item('contenttweaker:gravel_wool'))
    .chance(0.3f)
    .register()
inWorldCrafting.explosion.recipeBuilder()
    .input(item('mod_lavacow:holy_sludge'))
    .output(item('contenttweaker:holy_thing'))
    .chance(0.9f)
    .register()
inWorldCrafting.explosion.recipeBuilder()
    .input(item('minecraft:sapling', 1))
    .output(item('natura:nether_sapling', 1))
    .chance(0.05f)
    .register()
