inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('redstone'))
        .input(item('thermalfoundation:material', 16))
        .output(item('erebus:materials', 11))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('contenttweaker:bauxite_dust') * 2)
        .input(item('appliedenergistics2:material', 3))
        .input(item('minecraft:clay_ball'))
        .output(item('thermalfoundation:material', 68) * 3)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('napalm'))
        .input(item('contenttweaker:power_core_inactive'))
        .output(item('contenttweaker:power_core_active'))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('concrete'))
        .input(item('contenttweaker:electric_stone_dust') * 4)
        .input(item('contenttweaker:industrial_clay'))
        .output(item('projectred-core:resource_item') * 4)
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowstone'), 0.0f)
        .input(item('mekanism:ingot', 1))
        .output(item('contenttweaker:angel_ingot'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cloud_seed'), 0.0f)
        .input(item('mekanism:ingot', 1))
        .output(item('contenttweaker:angel_ingot'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('cloud_seed'), 0.0f)
        .input(item('mekanism:basicblock'))
        .output(item('contenttweaker:angel_block'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowstone'), 0.0f)
        .input(item('minecraft:gold_ingot'))
        .output(item('extrautils2:ingredients', 11))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowstone'), 0.0f)
        .input(item('minecraft:gold_block'))
        .output(item('extrautils2:simpledecorative', 1))
        .register()

inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('witchwater'), 0.1f)
        .input(item('minecraft:potato'))
        .output(item('minecraft:poisonous_potato'))
        .register()


inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('clay'))
        .input(item('contenttweaker:staffwood'))
        .input(item('tconstruct:dried_clay'))
        .output(item('contenttweaker:staffwood_clay'))
        .register()
inWorldCrafting.fluidToItem.recipeBuilder()
        .fluidInput(fluid('glowshroom_stew'))
        .input(item('contenttweaker:staffwood'))
        .input(item('contenttweaker:mushroomite_block'))
        .input(item('betternether:bone_mushroom'))
        .output(item('contenttweaker:staffwood_mushroom'))
        .register()