
mods.bloodmagic.meteor.remove(item('minecraft:diamond_block'))
mods.bloodmagic.meteor.remove(item('minecraft:iron_block'))
mods.bloodmagic.meteor.remove(item('minecraft:gold_block'))


mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity_custom', 35))
    .component(ore('blockMeteoritecobble'), 70)
    .radius(7)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()


mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity', 1))
    .component(ore('oreOverworldIron'), 50)
    .component(ore('denseOreIron'), 20)
    .component(ore('sandIron'), 30)
    .component(ore('oreOverworldNickel'), 30)
    .component(ore('denseOreNickel'), 10)
    .component(ore('oreOxideNickel'), 5)
    .component(ore('oreOverworldLead'), 20)
    .radius(8)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()

mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity', 7))
    .component(ore('oreEmerald'), 50)
    .component(ore('denseOreEmerald'), 20)
    .component(ore('oreChrome'), 15)
    .component(ore('oreVitriumTerrasteel'), 1)
    .component(ore('oreBeryllium'), 4)
    .component(ore('oreStoneleaf'), 10)
    .radius(8)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()
    
    
mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity', 22))
    .component(ore('oreOverworldSilver'), 50)
    .component(ore('denseOreSilver'), 20)
    .component(ore('oreErebusSilver'), 20)
    .component(ore('oreSpaceSilver'), 10)
    .component(ore('oreOverworldLead'), 20)
    .component(ore('oreOverworldGalena'), 20)
    .radius(8)
    .explosionStrength(10)
    .cost(100 * 1000)
    .register()

mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity_custom', 18))
    .component(ore('oreRuby'), 50)
    .component(ore('oreRedstone'), 30)
    .component(ore('oreGarstone'), 10)
    .component(ore('denseOreRedstone'), 5)
    .component(ore('oreBloodstone'), 4)
    .component(ore('oreLifeEssence'), 1)
    .radius(7)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()

mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity_custom', 79))
    .component(ore('oreBloodstone'), 50)
    .component(ore('oreLifeEssence'), 50)
    .radius(7)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()
    

mods.bloodmagic.meteor.recipeBuilder()
    .catalyst(item('extendedcrafting:singularity_custom', 98))
    .component(ore('oreCaelumite'), 50)
    .component(ore('oreErythynite'), 10)
    .component(ore('oreHallowsite'), 10)
    .component(ore('oreBenitoite'), 10)
    .component(ore('oreHellRuby'), 10)
    .component(ore('oreHellZanite'), 10)
    .radius(7)
    .explosionStrength(10)
    .cost(1000 * 1000)
    .register()
    

